# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.3'

gem 'pg',    '~> 1.1'
gem 'puma',  '~> 5.0'
gem 'rails', '~> 7.0.8', '>= 7.0.8.6'

# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

# CORS support
gem 'rack-cors'

# Faker for fixtures
gem 'faker'

# Timezone data for Windows
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Bootsnap to speed up boot time
gem 'bootsnap', require: false

# OAuth
gem 'omniauth', '~> 2.1' # maybe not needed?
gem 'omniauth-google-oauth2', '~> 1.1'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'rubocop', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-rails', require: false
  gem 'uuidtools'
end

group :development do
  gem 'letter_opener'
  # gem 'letter_opener_web'  # alternative inbox UI at /letter_opener
end
