name: Frontend Lint & Format Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/prettier.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Run Prettier/ESLint
        working-directory: frontend
        run: |
          npm ci
          npm run check-format       # your Prettier “--check” step
          npm run lint               # your ESLint step
